### ISSUE TITLE
Processing images with more than 256 cells

### ISSUE THREAD

**Issue by watsaig** [oist/Usiigaci#14]
Hi,

I'm curious whether Usiigaci can be applied to some images of ours that contain many cells (usually around 100 but up to 300), which sometimes exceeds the 8-bit limit on the labels. 

I read [here](https://github.com/oist/Usiigaci/issues/12#issuecomment-580776549) that you have a new implementation that supports more cells. Is this something you are planning on releasing soon? If not, I'm curious where the limitation is. Is it only the tracker? I had a quick look through the training and inference code and couldn't find anything that would indicate an 8 bit limit there, so if I just want to see how well images are segmented, can I use a 16-bit image for the labels?

Thanks!

**Comment by hftsai** [comment]
Hi yes, like you said this version is limited to 8 bit. 
It is related to the mask rcnn matterport part not the tracker part. 
This version of tracker should be able to deal with 16 bit without problem. the problem was at segmentation. 
we are working on new implementation on pytorch which is 16 bit.. but currently not yet ready to release. If you're good at modifying maskrcnn matterport or if you use maskrcnn benchmark to do segmentation, you should be able to get 16bit results to handle cell number up to 65000ish

**Comment by watsaig** [comment]
Ah good to know thank you. I think I'll patiently wait on the pytorch implementation, in the meantime we can make do with chopping up the images to ensure < 256 cells are visible in each one.
